### PR TITLE
[mwc-drawer] update CSS attributes

### PR DESCRIPTION
**Pull request by eskan**
update slot container style to allow slot to be correctly display with its own CSS.
https://material.io/develop/web/components/drawers/

### CODE REVIEW

**Comment by broken** [comment]
I was about to make the same PR. I'm glad I checked here beforehand. :)

**Comment by azakus** [comment]
Sorry for the delay, can you provide a screenshot or reproduction for the issue you're seeing?

**Comment by eskan** [comment]
Please take a look to the referenced issue  : https://github.com/material-components/material-components-web-components/issues/346

**Comment by asyncLiz** [comment]
Closing since this is out of date and was fixed in https://github.com/material-components/material-components-web-components/pull/588

**Pull request closed without merging**
