### PR TITLE
Added slotted icon to mwc-textfield

### LINKED ISSUE #760: mwc-textfield needs slots for icon and iconTrailing

### PR DESCRIPTION
**Pull request by maicol07**
Fixes #760

### CODE REVIEW

**Comment by maicol07** [comment]
`@googlebot I signed it!`

**Comment by dfreedm** [comment]
Hi. We're working on a more substantial refactor of textfield that may have what you need to include an icon, but it isn't in a shape yet where we have it in the repo.

Adding @asyncLiz to take a look and evaluate.

**Comment by maicol07** [comment]
Waiting you @asyncLiz!

**Comment by asyncLiz** [comment]
Hi, and thanks for the contribution! Sorry for the delay, this came right when I was out on medical leave. 

As Dan mentioned, I'm actively working on a pretty big refactor for text field right now that will include slotting icons. We really appreciate the contribution, but unfortunately it'll actually slow us down quite a bit right now to spend time reviewing, importing, maintaining, then migrating this solution to the new one.

We're targeting Q2 this year for text field to get the update (you'll see it land in MDC first), but it'll be coming real soon! It's my priority to finish since I got back last week 🙂

**Comment by maicol07** [comment]
@asyncLiz some months have passed since this PR was closed. Is the refactor completed? Can icons be slotted at the moment?

**Comment by maicol07** [comment]
@asyncLiz also Q2 has passed since June...

**Comment by asyncLiz** [comment]
Unfortunately things got shuffled around a bit with Material You, but text field is still being worked on :)

**Comment by maicol07** [comment]
> Unfortunately things got shuffled around a bit with Material You, but text field is still being worked on :)

I understand. But why don't you merge the PR in the meantime? This way we can use them, waiting the next update for textfield

**Comment by asyncLiz** [comment]
The reasons mentioned before still apply.

> We really appreciate the contribution, but unfortunately it'll actually slow us down quite a bit right now to spend time reviewing, importing, maintaining, then migrating this solution to the new one.

However, the great thing about web components is that you can subclass them! You can always extend the Textfield class and override `renderIcon()` to add in the capability to insert a `<slot>` 🙂

**Comment by maicol07** [comment]
> The reasons mentioned before still apply.
> 
> > We really appreciate the contribution, but unfortunately it'll actually slow us down quite a bit right now to spend time reviewing, importing, maintaining, then migrating this solution to the new one.
> 
> However, the great thing about web components is that you can subclass them! You can always extend the Textfield class and override `renderIcon()` to add in the capability to insert a `<slot>` 🙂

Oh, I didn't thought I could extend them. That's very good to use until you don't finish the refactor

**Pull request closed without merging**
