### PR TITLE
Circular Progress component implemented

### PR DESCRIPTION
**Pull request by timothyjoh**
Implemented the Circular indicator for progress as a LitElement component

https://material.io/design/components/progress-indicators.html#circular-progress-indicators

### CODE REVIEW

**Comment by luissardon** [comment]
I'm ok with my commits being contributed to this project.

**Comment by jhnsntmthy** [comment]
If you all can get this merged in, or some feedback, we got plenty more components to send you. I'll resubmit the Select, Textfield, etc that we have been working on fixes for

**Comment by azakus** [comment]
Sorry for the delay, Circular Progress has had a redesign recently. Would you be willing to update this PR to reflect that once the design is updated?

**Comment by asyncLiz** [comment]
Thanks for the PR! We're currently working on an implementation for circular progress. Follow #500 for updates 😊

**Pull request closed without merging**
