### PR TITLE
Fix Issue #55

### PR DESCRIPTION
**Pull request by suburbanworrier**
Update css class for stroked buttons from `mdc-button--stroked` to `mdc-button--outlined` per new mdc-button

### CODE REVIEW

**Comment by suburbanworrier** [comment]
suburbanworrier _has_ signed the CLA

**Comment by suburbanworrier** [comment]
_All_ of my users have now signed the CLA

**Comment by suburbanworrier** [comment]
All authors are ok with their commits being contributed to this project

**Comment by MatthewBracewell** [comment]
This author consents to his commits being contributed to the project.

**Comment by frankiefu** [comment]
Fixed by https://github.com/material-components/material-components-web-components/commit/dda468342f29d431b6ea557ec9d2554cf276fdc5#diff-5a214fb1e9ee378db676acce7195368f

**Pull request closed without merging**
