### PR TITLE
Select, Menu and List Component to Lit-Element in TS

### PR DESCRIPTION
**Pull request by timothyjoh**
Select (which depends on Menu and List Components) built in TS

We saw no specific work being done on these, and have a few more to send as well. I will make other PRs for each set.

### CODE REVIEW

**Comment by jhnsntmthy** [comment]
CLAs should be all signed

**Comment by luissardon** [comment]
confirm CLA

**Comment by rodanato** [comment]
confirm CLA

**Comment by mercmobily** [comment]
Oh this is so awesome. Any chance to get this included into the list of official components? How many times have you seen an app without a select?

**Comment by jhnsntmthy** [comment]
We will update with some changes, and update from the upstream, and create a new PR here in the coming week

**Comment by jurajbak** [comment]
Hi, any news about this PR? It's one year old.

**Comment by fernandopasik** [comment]
Since this one landed in https://github.com/material-components/material-components-web-components/pull/763 maybe this ticket should be closed? @e111077

**Pull request closed without merging**
