### PR TITLE
Uprade to typescript 4x

### PR DESCRIPTION
**Pull request by taylor-vann**
Migration from 0.19.1 -> 0.20.0

### CODE REVIEW

**Review by e111077 — APPROVED** [review]

**Comment by asyncLiz** [comment]
If this PR is updating typescript, I would expect to see a change for the root [package.json](https://github.com/material-components/material-components-web-components/blob/master/package.json#L97) bumping the typescript dependency

**Comment by e111077** [comment]
IIRC this is a fix of an issue in #1863

**Comment by dfreedm** [comment]
Let's not rev package version with the typescript update. Also, this needs to be sync'd against master

**Comment by e111077** [comment]
Wait, something weird is going on...

#1863 was merged via copybara which has a change to `/package.json` to update ts to 4.0. All other changes (the ones in google3 🙄) seem to have merged but not the one to the `package.json` which is in the root.

This CL was just meant to initially prepare for release and update the changelog, but Liz noticed that `/package.json` did not have an updated `typescript` dependency.

What needs to happen is we need to update the TS dependency in the root package without Copybara and then use this (or something like this) PR to ready for release

**Comment by taylor-vann** [comment]
Closing for sanity reasons.
Will make separate PR for package json Typescript bump.
Will make separate PR after for new release.

**Pull request closed without merging**
