### PR TITLE
mwc-layout-grid

### PR DESCRIPTION
**Pull request by jurajbak**
Created new mwc-layout-grid component. It's not on your list of components, but it seems to me as a common thing which should not be missing in a library.

Btw. do you have any roadmap for material-components-web-components? Or what are the plans for the future?

### CODE REVIEW

**Comment by jurajbak** [comment]
@googlebot I signed it!

**Comment by e111077** [comment]
Thank you for the PR, but we have decided that we are only supporting components from MDC. Though, please feel empowered to release this component on your own

**Comment by jurajbak** [comment]
It's already based on MDC. https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid

**Comment by asyncLiz** [comment]
Thanks for pointing that out! At the moment we are focused on implementing the components in our README roadmap first, but I've created #844 to track this one.

This one is lower priority since there are a lot of great CSS grid systems out there already that you can use in your apps.

**Pull request closed without merging**
