### PR TITLE
Edge support

### PR DESCRIPTION
**Pull request by asyncLiz**
Wait until #947 for internal changes first.

### CODE REVIEW

**Comment by dfreedm** [comment]
Let's add Edge 80 testing on saucelabs

**Comment by asyncLiz** [comment]
Specifically v80, or the latest Edge available?

**Comment by dfreedm** [comment]
Looks like 80 is the latest available on saucelabs

**Comment by asyncLiz** [comment]
I meant do you want

```
      'sl-edge-80': {
        base: 'SauceLabs',
        browserName: 'microsoftedge',
        version: '80',
        platform: 'Windows 10',
      },
```
or
```
      'sl-edge': {
        base: 'SauceLabs',
        browserName: 'microsoftedge',
        version: 'latest',
        platform: 'Windows 10',
      },
```

**Comment by dfreedm** [comment]
Oh yeah, let's try "latest"

**Pull request merged**
