### PR TITLE
mwc-checkbox: normalise tests

### PR DESCRIPTION
**Pull request by 43081j**
This is just normalising the tests and adding a few assertions to match with what i did last time i reworked all the tests (added a "factory" kind of pattern).

### CODE REVIEW

**Comment by 43081j** [comment]
FYI i ran tests on master too and got the same test failure so not too sure whats up.

**Comment by e111077** [comment]
Heya, James, this looks generally good; there seems to be a CI failure in one test but I'm rerunning the job. Next I'm going to run it through internal coverage tests to give it a final check.

**Comment by e111077** [comment]
If this tests fails again, try rebasing onto master?

**Comment by e111077** [comment]
Seems like the same failure. Can you please give it a quick
`git checkout master && git pull && git checkout checkbox-tests && git rebase master`

**Comment by 43081j** [comment]
have rebased it now 👍  ill see if CI fails and try debug it a bit if it does. weirdly i was getting the same failure on my master branch so im hoping it just fixes itself tbh 🙈

**Comment by 43081j** [comment]
good news! it now passes on `master` locally but not on my branch. so ill try debug it a bit 

very weird since that test hasn't changed, the only change is that it uses a fixture now rather than `createElement` 🤔 

i wonder if before this test passed because of timings... we are now waiting longer maybe so `update` has run and set the animation class. im not entirely sure

**Comment by e111077** [comment]
sorry this slipped through; I'll be able to take a closer look soon

**Comment by 43081j** [comment]
No rush I'll see if I can get chance to debug it too 👍 thanks for taking time to look

**Comment by e111077** [comment]
Dan wrote this test and I think it just may have bugs. I think it's trying to do the following:

```diff
test('does not animate after being hidden', async () => {
      element.checked = true;
+     const animatedElement = element.shadowRoot!.querySelector('.mdc-checkbox__background')!;
+     await new Promise((resolve) => {
+       animatedElement.addEventListener('animationend', resolve);
+     });
+     await element.updateComplete;
      element.style.display = 'hidden';
      await rafPromise();
      element.style.display = '';
      await rafPromise();
      assert.equal(internals.animationClass, '');
    });
```

Write that into the test (but formatted) and that should fix the issue. I'll bring it up with him when Dan is back from vacation next week.

**Comment by 43081j** [comment]
i made the change and the tests pass for me now... but i have no idea still what that test is trying to test 😂

**Comment by e111077** [comment]
I vaguely remember internally we were having an issue where on page load or when going from hidden to not hidden, the initial "check" animation would play every time. I think this was what it was testing in particular because it was added with the `@transitionend` callback

**Comment by e111077** [comment]
FF failure. Rerunning to se if flake

**Pull request merged**
