### PR TITLE
test(fab): rework tests to use fixtures

### PR DESCRIPTION
**Pull request by 43081j**
have done the same i did with the other tests:

- moved them to use fixtures
- added assertions for the initial values
- added tests for `reducedTouchTarget`

cc @e111077

### CODE REVIEW

**Review by dfreedm — APPROVED** [review]
LGTM. Throwing onto the internal testing train

**Comment by 43081j** [comment]
Looks like tests failed in the internal pr. Can try take a look tomorrow unless you already have an idea of what's up

**Comment by dfreedm** [comment]
Thankfully its failing on IE11, not something internal-only. Our Saucelabs runner only runs for PRs on branches in the repo.

**Comment by 43081j** [comment]
@dfreedm  i suspect this is because ie11 is unhappy with camel case attributes and mapping them to properties, somehow.

i will update to use properties for those, but the intention was to assert that attributes set properties correctly, so we would lose that.

**Comment by 43081j** [comment]
@dfreedm @e111077 could one of you re-run the internal CI stuff when you get chance so we can merge this? 🙏 

it should pass now

**Comment by dfreedm** [comment]
Looks good. We have a slightly different way of handling dependencies internally, and because of some quirks with our github sync system and manual internal fixes, this will land in #2413 with no files changed 🤷

**Pull request merged**
