### PR TITLE
Implemented MDC Card Components

### PR DESCRIPTION
**Pull request by zoofadoofa**
PR for issue [#231](https://github.com/material-components/material-components-web-components/issues/231)

Implemented:
- implement in typescript
- mwc-card
  - change stroke to outlined to match MDC
  - add border-top-left, border-top-right, border-bottom-right, border-bottom-left as css properties
  - add readme
- mwc-card-primary-action
  - add slot for content
  - add readme
- mwc-card-meda
  - add aspectRatio
    - square
    - 16-9
  - add slot for content over image
  - add background-image as a css-property
  - add border-top-left, border-top-right, border-bottom-right, border-bottom-left as css properties
  - add readme
- mwc-card-actions
  - add fullBleed
  - add slot for buttons
  - add slot for icons
  - add readme
- update card demo
- update card unit test
- upgrade to mdc card 0.44.0

### CODE REVIEW

**Comment by Pike** [comment]
Would you need to add the tests here to

https://github.com/material-components/material-components-web-components/blob/17c741fd38d22ae761d90301b9735941fd4cfb0b/karma.conf.js#L88

to actually get them run?

**Comment by zoofadoofa** [comment]
@Pike as a part of merging in the 1.0.0 updates I added card to karma and verified the test ran.
Thanks for the feedback.

**Comment by Pike** [comment]
Toying around with your branch, I found one more hard-coded list if packages,

https://github.com/material-components/material-components-web-components/blob/17c741fd38d22ae761d90301b9735941fd4cfb0b/scripts/publish-demos.sh#L42

**Comment by e111077** [comment]
Hello, can you please rebase and run through the formatter (`npm run format`) and change the layout until the formatter spits out something you like?

**Comment by azakus** [comment]
Does this make #231 obsolete?

**Comment by e111077** [comment]
basically, but there's a bit more work needed to be done.

**Comment by zoofadoofa** [comment]
@e111077 I will work on getting what you requested together over the next few nights. hopefully have it ready by end of week.

**Comment by e111077** [comment]
Heya, thanks again for your work! The points that you brought up have left us engineers on the team with quite a lot of design questions. We are going to escalate this up to the design team so that we can get better clarification on how card should be used.

Additionally, mwc-card is basically begging for a design doc, so we will have to hash this out with design a bit more. Until then, unfortunately, this PR is stalled.

In the meanwhile, do you think it would be possible to clean up the commit history? There seems to be about ~400 changed files and some conflicts. If the git-fu isn't strong, it's always possible to start a new PR.

**Comment by zoofadoofa** [comment]
I was actually going to ask if I could start a new PR considering most of the conflicts are more related to the age of the PR. I'll work on getting a new PR

**Comment by zoofadoofa** [comment]
managed to fix everything with git but PR closed at some point because of 0 commits while i was resetting. new PR can be located here #445

**Pull request closed without merging**
