### PR TITLE
Update Read.me to include mwc-select

### PR DESCRIPTION
**Pull request by davie-robertson**
Updated status of mwc-select component

### CODE REVIEW

**Comment by fernandopasik** [comment]
please could you add mwc-list and  mwc-menu as well?

**Comment by fernandopasik** [comment]
@e111077 maybe can check this one

**Comment by e111077** [comment]
Sorry been heads down in landing Select. Thanks for the heads up

**Comment by fernandopasik** [comment]
Thanks for reviewing it super fast @e111077 !

**Pull request merged**
