### PR TITLE
Remove circular dependency from <mwc-radio> by merging selection-controller into base.

### PR DESCRIPTION
**Pull request by aomarks**
Remove circular dependency from <mwc-radio> by merging selection-controller into base.

### CODE REVIEW

**Comment by jsilvermist** [comment]
Out of curiosity, is this being done for best practice? Or is it due to it causing an error with something?

**Comment by aomarks** [comment]
> Out of curiosity, is this being done for best practice? Or is it due to it causing an error with something?

It's due to some internal Google infrastructure that prefers not to deal with circular dependencies. Normally this style would be completely fine for TypeScript and ES modules.

**Comment by aomarks** [comment]
@rictic review request (I can't actually add you since you aren't a collaborator, but I sent an invite).

**Comment by rictic** [comment]
As I recall, the internal infra (that I think is open sourced as the bazel TypeScript rules) does work fine with circular dependencies within an individual ts_library, it just can't have them between ts_libraries

**Pull request merged**
