### PR TITLE
Fix #669

### LINKED ISSUE #669: Why the plain keyframe in the head tag?
I'm not sure if it is a bug; Why the plain keyframe in the head tag?

Screenshot 2019-11-30 at 23 25 17

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #669

### CODE REVIEW

**Comment by e111077** [comment]
github seems to be acting up

**Comment by e111077** [comment]
@aomarks When you're awake, can you TAL @ the GH workflow? It won't let me cancel the workflow or rerun it.

**Comment by aomarks** [comment]
> @aomarks When you're awake, can you TAL @ the GH workflow? It won't let me cancel the workflow or rerun it.

Oops, the problem is that I didn't set up the new GH action test script to work correctly for PRs from forks, since Sauce credentials can't be available:

image

I'll send a PR so that we only try to run Sauce on non-forked PRs.

**Comment by aomarks** [comment]
@abdonrd mind merging master into your branch to bring in the new GH action script?

**Comment by abdonrd** [comment]
@e111077 @aomarks Travis is happy now!

**Comment by abdonrd** [comment]
Will there be any release soon? Thanks in advance!

**Comment by e111077** [comment]
Probably not until next week

**Comment by abdonrd** [comment]
@e111077 I imagine there will be no release today that is Friday, right?

**Comment by e111077** [comment]
😬😬😬 you're right. We need to start a regular release schedule. Sorry about that. I'll make sure to set myself a reminder

**Comment by abdonrd** [comment]
Thanks @e111077! 😄

**Pull request merged**
