### PR TITLE
TopAppBar: remove extra row

### PR DESCRIPTION
**Pull request by straversi**
Remove "extra row" functionality from top app bar.

fixes: #197

### CODE REVIEW

**Comment by zoofadoofa** [comment]
How are you going to insert tabs into top-app-bar if you remove this slot? If the issue is with styling in regards to prominent you only need to remove the 'mdc-top-app-bar__section' from the extra row and prominent will work nicely

**Comment by frankiefu** [comment]
[pwa-starter-kit](https://pwa-starter-kit.appspot.com) also needs "extra row" (or something equivalent)  to insert tabs into top-app-bar.

**Comment by straversi** [comment]
Seems like we should re-evaluate #197. I'll add concerns there.

**Comment by straversi** [comment]
Reviewed this further, and we preempted MDC Web by implementing this feature. We'd like to avoid that, so we're going to remove the `extraRow` property for now and reintroduce when MDC Web releases it.

**Pull request merged**
